[package]
name = "shadowself"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
reqwest = "0.11.23"
windows = "0.52.0"
tokio = { version = "1", features = ["full"] }
